### ISSUE TITLE
Is there an ebuild for this tool?

### ISSUE THREAD

**Issue by Gooberpatrol66** [geaaru/node-ebuilder#4]
Is it possible to install this from portage?

**Comment by geaaru** [comment]
Hi,

not for now. But I will push ebuild soon to my [overlay](https://github.com/geaaru/geaaru_overlay)

**Comment by geaaru** [comment]
Hi, bumped v.0.2.2 and created ebuild under geaaru-overlay.

Currently, the package doesn't contain a config file as an example. You can use file that is available on master upstream.

Thanks
